### ISSUE TITLE
Make tag sub-categories as "subdirs" rather than prefixes on card names

### ISSUE THREAD

**Issue by MisterSeajay** [Haoming02/sd-webui-easy-tag-insert#5]
UI enhancement request:

Take this example YAML, where **Cats** and **Dogs** are sub-categories of **Pets**:

```
Pets:
  Cats:
    Garfield: A cute oversized orange tomcat with black stripes
    Nermal: A cute grey kitten
  Dogs:
    Odie: A yellow dog with long tongue
People:
  Jon: A middle aged man with short brown curly hair
```

The effect of nesting tags in the YAML is that only the top-level categories (**Pets** and **People**) are shown as "subdirs" within the ribbon above the cards, with the sub-categories pre-fixed to the tag name on the actual "card":

> [all] [Pets] [People]
> ----
> [Cats/Garfield] [Cats/Nermal] [Dogs/Odie] [Jon]

This makes it slightly harder to read the cards/find tags. When the sub-categories are longer than a few characters the end of the tag name is cropped at the right hand end of the card. I was hoping that the sub-categories would be suffixed to the parent category. In other words, what I would prefer to see is:

> [all] [Pets/Cats] [Pets/Dogs] [People]
> ----
> [Garfield] [Nermal] [Odie] [Jon]

This behavior is similar to what happens in other Extra Networks, such as LoRAs, when they are organized into sub-dirs.
